version: '2'
 
volumes:
  orderer.example.com:
  orderer2.example.com:
  orderer3.example.com:
  orderer4.example.com:
  orderer5.example.com:
 
networks:
  byfn:
 
services:
  orderer.example.com:
    extends:
      file: docker-compose-base.yaml
      service: orderer-base
    container_name: orderer.example.com
    extra_hosts:
      - "peer0.org1.example.com:${ORG11}"
      - "peer1.org1.example.com:${ORG12}"
      - "peer0.org2.example.com:${ORG21}"
      - "peer1.org2.example.com:${ORG22}"
    networks:
      - byfn
    volumes:
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/:/var/hyperledger/orderer/tls
      - orderer.example.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
 
  orderer2.example.com:
    extends:
      file: docker-compose-base.yaml
      service: orderer-base
    container_name: orderer2.example.com
    extra_hosts:
      - "peer0.org1.example.com:${ORG11}"
      - "peer1.org1.example.com:${ORG12}"
      - "peer0.org2.example.com:${ORG21}"
      - "peer1.org2.example.com:${ORG22}"
    networks:
      - byfn
    volumes:
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/example.com/orderers/orderer2.example.com/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/example.com/orderers/orderer2.example.com/tls/:/var/hyperledger/orderer/tls
      - orderer2.example.com:/var/hyperledger/production/orderer
    ports:
      - 8050:7050
 
  orderer3.example.com:
    extends:
      file: docker-compose-base.yaml
      service: orderer-base
    container_name: orderer3.example.com
    extra_hosts:
      - "peer0.org1.example.com:${ORG11}"
      - "peer1.org1.example.com:${ORG12}"
      - "peer0.org2.example.com:${ORG21}"
      - "peer1.org2.example.com:${ORG22}"
    networks:
      - byfn
    volumes:
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/example.com/orderers/orderer3.example.com/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/example.com/orderers/orderer3.example.com/tls/:/var/hyperledger/orderer/tls
      - orderer3.example.com:/var/hyperledger/production/orderer
    ports:
      - 9050:7050
 
  orderer4.example.com:
    extends:
      file: docker-compose-base.yaml
      service: orderer-base
    container_name: orderer4.example.com
    extra_hosts:
      - "peer0.org1.example.com:${ORG11}"
      - "peer1.org1.example.com:${ORG12}"
      - "peer0.org2.example.com:${ORG21}"
      - "peer1.org2.example.com:${ORG22}"
    networks:
      - byfn
    volumes:
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/example.com/orderers/orderer4.example.com/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/example.com/orderers/orderer4.example.com/tls/:/var/hyperledger/orderer/tls
      - orderer4.example.com:/var/hyperledger/production/orderer
    ports:
      - 10050:7050
 
  orderer5.example.com:
    extends:
      file: docker-compose-base.yaml
      service: orderer-base
    container_name: orderer5.example.com
    extra_hosts:
      - "peer0.org1.example.com:${ORG11}"
      - "peer1.org1.example.com:${ORG12}"
      - "peer0.org2.example.com:${ORG21}"
      - "peer1.org2.example.com:${ORG22}"
    networks:
      - byfn
    volumes:
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/example.com/orderers/orderer5.example.com/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/example.com/orderers/orderer5.example.com/tls/:/var/hyperledger/orderer/tls
      - orderer5.example.com:/var/hyperledger/production/orderer
    ports:
      - 11050:7050