version: '2.2'

services:
        filebeat:
                image: docker.elastic.co/beats/filebeat:7.2.0
                container_name: filebeat
                command: filebeat -e -strict.perms=false
                volumes:
                        - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
                        - /var/run/docker.sock:/var/run/docker.sock
                        - /home/an/GCP_Hyperledger/vm/org1-1/log:/var/log
